services:
  - type: web
    name: my-dotnet-app
    env: bash
    buildCommand: |
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet
      dotnet publish -c Release -o out
    startCommand: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet
      dotnet out/wennovation-hub.dll
    branch: main
    region: oregon
    plan: free
